#!/usr/bin/env python3
"""
WishlistOps CLI Onboarding - Interactive setup wizard for first-time users.
Guides users through environment configuration with helpful prompts and validation.
"""

import os
import sys
from pathlib import Path
from typing import Optional, Dict
import re

# Set UTF-8 encoding for Windows
if sys.platform == 'win32':
    import codecs
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'strict')
    sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'strict')


class Colors:
    """Terminal colors for better UX"""
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    END = '\033[0m'


def print_header(text: str):
    """Print formatted header"""
    print(f"\n{Colors.BOLD}{Colors.BLUE}{'=' * 70}{Colors.END}")
    print(f"{Colors.BOLD}{Colors.CYAN}{text}{Colors.END}")
    print(f"{Colors.BOLD}{Colors.BLUE}{'=' * 70}{Colors.END}\n")


def print_success(text: str):
    """Print success message"""
    print(f"{Colors.GREEN}✓ {text}{Colors.END}")


def print_error(text: str):
    """Print error message"""
    print(f"{Colors.RED}✗ {text}{Colors.END}")


def print_info(text: str):
    """Print info message"""
    print(f"{Colors.CYAN}ℹ {text}{Colors.END}")


def print_warning(text: str):
    """Print warning message"""
    print(f"{Colors.YELLOW}⚠ {text}{Colors.END}")


def prompt_input(prompt: str, default: str = "", required: bool = True, secret: bool = False) -> str:
    """
    Prompt user for input with validation.
    
    Args:
        prompt: Prompt text
        default: Default value
        required: Whether input is required
        secret: Whether to hide input (for passwords/API keys)
    """
    default_text = f" [{default}]" if default else ""
    required_mark = " *" if required else ""
    
    while True:
        try:
            if secret:
                import getpass
                value = getpass.getpass(f"{prompt}{default_text}{required_mark}: ")
            else:
                value = input(f"{prompt}{default_text}{required_mark}: ").strip()
            
            if not value and default:
                return default
            
            if not value and required:
                print_error("This field is required. Please enter a value.")
                continue
            
            return value
        except KeyboardInterrupt:
            print("\n\n" + Colors.YELLOW + "Setup cancelled by user." + Colors.END)
            sys.exit(0)


def validate_url(url: str) -> bool:
    """Validate URL format"""
    pattern = re.compile(r'^https?://[\w\-._~:/?#[\]@!$&\'()*+,;=.]+$')
    return bool(pattern.match(url))


def validate_app_id(app_id: str) -> bool:
    """Validate Steam App ID"""
    return app_id.isdigit() and 3 <= len(app_id) <= 7


def validate_path(path: str) -> bool:
    """Validate directory path"""
    return Path(path).exists() and Path(path).is_dir()


def load_existing_env() -> Dict[str, str]:
    """Load existing .env file if it exists"""
    env_file = Path.cwd() / ".env"
    env_vars = {}
    
    if env_file.exists():
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key.strip()] = value.strip()
    
    return env_vars


def save_env(env_vars: Dict[str, str]):
    """Save environment variables to .env file"""
    env_file = Path.cwd() / ".env"
    
    with open(env_file, 'w') as f:
        f.write("# WishlistOps Environment Configuration\n")
        f.write("# Generated by onboarding wizard\n")
        f.write(f"# Date: {Path.cwd()}\n\n")
        
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    print_success(f"Environment saved to: {env_file}")


def welcome_screen():
    """Display welcome message"""
    print("\n" + Colors.BOLD + Colors.CYAN)
    print("  ╔══════════════════════════════════════════════════════════════════╗")
    print("  ║                                                                  ║")
    print("  ║              🎮  Welcome to WishlistOps Setup  🎮                ║")
    print("  ║                                                                  ║")
    print("  ║        Automate Your Steam Marketing in Minutes                 ║")
    print("  ║                                                                  ║")
    print("  ╚══════════════════════════════════════════════════════════════════╝")
    print(Colors.END)
    
    print(f"\n{Colors.BOLD}What is WishlistOps?{Colors.END}")
    print("  • Automatically generates Steam announcements from your Git commits")
    print("  • Creates beautiful AI-powered banners for your game")
    print("  • Sends announcements to Discord for approval before posting\n")
    
    print(f"{Colors.BOLD}This wizard will help you:{Colors.END}")
    print("  1. Set up your API keys (Steam, Google AI, Discord)")
    print("  2. Configure your game's branding and voice")
    print("  3. Set automation preferences\n")
    
    response = input(f"{Colors.BOLD}Ready to get started? (yes/no): {Colors.END}").lower()
    if response not in ['yes', 'y']:
        print(Colors.YELLOW + "\nSetup cancelled. Run 'wishlistops setup' when you're ready!" + Colors.END)
        sys.exit(0)


def setup_steam():
    """Setup Steam API configuration"""
    print_header("🎮 Steam Configuration")
    
    print_info("You'll need:")
    print("  • Steam Web API Key (from https://steamcommunity.com/dev/apikey)")
    print("  • Your game's App ID (from Steamworks Partner dashboard)\n")
    
    # API Key
    api_key = prompt_input(
        "Steam Web API Key",
        secret=True,
        required=True
    )
    
    # App ID
    while True:
        app_id = prompt_input("Steam App ID (6-7 digits)")
        if validate_app_id(app_id):
            break
        print_error("Invalid App ID. Must be 6-7 digits.")
    
    # App Name
    app_name = prompt_input("Game Name")
    
    print_success("Steam configuration complete!")
    
    return {
        'STEAM_API_KEY': api_key,
        'STEAM_APP_ID': app_id,
        'STEAM_APP_NAME': app_name
    }


def setup_google_ai():
    """Setup Google AI configuration"""
    print_header("🤖 Google AI Configuration")
    
    print_info("Google AI generates your announcement text and banners.")
    print("  Get your API key from: https://makersuite.google.com/app/apikey\n")
    
    api_key = prompt_input(
        "Google AI API Key",
        secret=True,
        required=True
    )
    
    print_success("Google AI configuration complete!")
    
    return {'GOOGLE_API_KEY': api_key}


def setup_discord():
    """Setup Discord webhook configuration"""
    print_header("💬 Discord Configuration")
    
    print_info("Discord webhooks let you review announcements before posting.")
    print("  Create a webhook in Discord: Server Settings → Integrations → Webhooks\n")
    
    use_discord = prompt_input("Do you want to use Discord for approvals? (yes/no)", default="yes").lower()
    
    if use_discord in ['yes', 'y']:
        while True:
            webhook = prompt_input("Discord Webhook URL", required=False)
            if not webhook or validate_url(webhook):
                break
            print_error("Invalid URL format.")
        
        if webhook:
            print_success("Discord configuration complete!")
            return {'DISCORD_WEBHOOK_URL': webhook}
    
    print_warning("Skipping Discord setup. You can add it later.")
    return {}


def setup_repository():
    """Setup Git repository path"""
    print_header("📁 Repository Configuration")
    
    print_info("WishlistOps monitors your Git commits to generate announcements.\n")
    
    # Try to detect current directory
    cwd = Path.cwd()
    git_dir = cwd / ".git"
    
    if git_dir.exists():
        print_success(f"Git repository detected: {cwd}")
        use_current = prompt_input("Use this directory?", default="yes").lower()
        if use_current in ['yes', 'y']:
            return {'REPO_PATH': str(cwd)}
    
    while True:
        repo_path = prompt_input("Git Repository Path")
        if validate_path(repo_path):
            git_check = Path(repo_path) / ".git"
            if git_check.exists():
                break
            print_warning(f"No .git directory found in {repo_path}")
            continue_anyway = prompt_input("Continue anyway?", default="no").lower()
            if continue_anyway in ['yes', 'y']:
                break
        print_error("Directory not found.")
    
    print_success("Repository configuration complete!")
    return {'REPO_PATH': repo_path}


def summary_screen(env_vars: Dict[str, str]):
    """Display configuration summary"""
    print_header("📋 Configuration Summary")
    
    print(f"{Colors.BOLD}Your configuration:{Colors.END}\n")
    
    # Steam
    print(f"{Colors.CYAN}Steam:{Colors.END}")
    print(f"  App ID: {env_vars.get('STEAM_APP_ID', 'Not set')}")
    print(f"  App Name: {env_vars.get('STEAM_APP_NAME', 'Not set')}")
    print(f"  API Key: {'✓ Configured' if env_vars.get('STEAM_API_KEY') else '✗ Not set'}\n")
    
    # Google AI
    print(f"{Colors.CYAN}Google AI:{Colors.END}")
    print(f"  API Key: {'✓ Configured' if env_vars.get('GOOGLE_API_KEY') else '✗ Not set'}\n")
    
    # Discord
    print(f"{Colors.CYAN}Discord:{Colors.END}")
    print(f"  Webhook: {'✓ Configured' if env_vars.get('DISCORD_WEBHOOK_URL') else '✗ Not set'}\n")
    
    # Repository
    print(f"{Colors.CYAN}Repository:{Colors.END}")
    print(f"  Path: {env_vars.get('REPO_PATH', 'Not set')}\n")


def next_steps():
    """Display next steps"""
    print_header("🎉 Setup Complete!")
    
    print(f"{Colors.BOLD}Next steps:{Colors.END}\n")
    
    print("1. Configure your game's branding:")
    print(f"   {Colors.CYAN}wishlistops configure{Colors.END}\n")
    
    print("2. Test your setup:")
    print(f"   {Colors.CYAN}wishlistops test{Colors.END}\n")
    
    print("3. Start the server:")
    print(f"   {Colors.CYAN}wishlistops serve{Colors.END}\n")
    
    print("4. Or run a dry-run:")
    print(f"   {Colors.CYAN}wishlistops run --dry-run{Colors.END}\n")
    
    print(f"{Colors.BOLD}Need help?{Colors.END}")
    print(f"  • Documentation: {Colors.CYAN}wishlistops docs{Colors.END}")
    print(f"  • Configuration: Your settings are saved in {Colors.CYAN}.env{Colors.END}")
    print(f"  • Dashboard: Open {Colors.CYAN}dashboard/index.html{Colors.END} in your browser\n")


def main():
    """Main onboarding flow"""
    try:
        # Check if already configured
        existing_env = load_existing_env()
        
        if existing_env:
            print_warning("Existing configuration found.")
            reconfigure = prompt_input("Do you want to reconfigure?", default="no").lower()
            if reconfigure not in ['yes', 'y']:
                print_info("Keeping existing configuration.")
                sys.exit(0)
        
        # Welcome
        welcome_screen()
        
        # Collect configuration
        env_vars = {}
        
        # Steam setup
        env_vars.update(setup_steam())
        
        # Google AI setup
        env_vars.update(setup_google_ai())
        
        # Discord setup (optional)
        env_vars.update(setup_discord())
        
        # Repository setup
        env_vars.update(setup_repository())
        
        # Summary
        summary_screen(env_vars)
        
        # Confirm and save
        confirm = prompt_input("\nSave this configuration?", default="yes").lower()
        if confirm in ['yes', 'y']:
            save_env(env_vars)
            next_steps()
        else:
            print_warning("Configuration not saved.")
            sys.exit(0)
    
    except Exception as e:
        print_error(f"Setup failed: {e}")
        sys.exit(1)


if __name__ == '__main__':
    main()
